import type { NextPage } from "next";
import Head from "next/head";

import styles from "../styles/Home.module.css";
import Poll from "./Poll";

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>CORD TEST APP</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <Poll />
            </main>
        </div>
    );
};

export default Home;
